language: java

services:
 - cassandra

before_install: |-
 cqlsh -e "SOURCE 'crudmicroservices-middle/src/cassandra/cql/exec.cql';"

install: mvn install -Ptravis -X

script: mvn -Ptravis test -X
jdk:
 - oraclejdk8

after_success:
 - mvn clean
