version: '2'
services:
  eureka:
    image: netflixoss/eureka:1.3.1
    ports:
      - "8080:8080"
  zuul:
    image: netflixoss/zuul:1.0.28
    ports:
      - "9090:8080"
    depends_on:
      - eureka
    links:
      - eureka
    environment:
      - eureka.serviceUrl.default=http://eureka:8080/eureka/v2/
      - origin.zuul.client.DeploymentContextBasedVipAddresses=crudmicroservicesedge.matera.com
  cassandra:
    image: spotify/cassandra
  crudmicroservices-middle:
    image: crudmicroservices-middle:latest
    depends_on:
      - eureka
      - cassandra
    links:
      - eureka
      - cassandra
    command: ./wait-for-it.sh -t 0 cassandra:9042 -- cqlsh schema.cql
  crudmicroservices-edge:
    image: crudmicroservices-edge:latest
    links:
      - eureka
    depends_on:
      - eureka
